### ISSUE TITLE
autoplayTimeout not working

### ISSUE THREAD

**Issue by lukadriel7** [Wlada/vue-carousel-3d#101]
Hello  and thank you for your work. I have been trying to increase the autoplay timeout with no success. It stays 2000 ms. I use it directly in my html code without any modification

**Comment by jodak94** [comment]
same problem.

**Comment by aurelie-brebant** [comment]
Hi @lukadriel7! Facing the same issue, could you share how you fixed it please? 
Thank you

**Comment by lukadriel7** [comment]
Hello @aurelie-brebant , sorry it has been so long I don't remember.
I went to see in my old repo and this is the code I used
`<carousel-3d :height="cardheight" :autoplay="true" :space="space" :autoplay-timeout="6000">`
I don't know exactly what went wrong at the time. Maybe you can put your code here ?
Hope it can help.

**Comment by lukadriel7** [comment]
@aurelie-brebant looking back at the docs, I think I was using a camelCase for the attribute instead of a kebab-case

**Comment by aurelie-brebant** [comment]
Hi @lukadriel7, you're right, indeed in the docs it seems that they use camelCase (autoplayTimeout), but changing for kebab-case as you mentioned did the work, thank you for your reactivity !
