### ISSUE TITLE
v0.1.21: swiping movement reversed

### ISSUE THREAD

**Issue by shouki-s** [Wlada/vue-carousel-3d#113]
I found the movement when swiping is reversed after v0.1.21.

v0.1.20: When swiping from right to left, the slide moves right to left.
v0.1.21: When swiping from right to left, the slide moves **left to right**.

This change was assumed?

I think the cause is here.
https://github.com/Wlada/vue-carousel-3d/pull/90/files#diff-8f21bb4aa597635c487512cd817d9b3bR36

v0.1.20:
```javascript
const rIndex = this.getSideIndex(this.parent.rightIndices)
const lIndex = this.getSideIndex(this.parent.leftIndices)
```

v0.1.21:
```javascript
const rIndex = this.leftIndex
const lIndex = this.rightIndex
```

**Comment by sowinski** [comment]
Same here. 
@shouki-s Did you fix this issue?

**Comment by shouki-s** [comment]
@sowinski Now, I created PR https://github.com/Wlada/vue-carousel-3d/pull/116.

**Comment by Wlada** [comment]
Thanks for  your contribution
