### ISSUE TITLE
mobile  Initialization does not show the transform property

### ISSUE THREAD

**Issue by hwyw** [Wlada/vue-carousel-3d#13]
Hi, I met a problem

Initialization does not show the  transform property, only switch the viewport can be displayed correctly, such as iphone6 to iphone5 , iphone5 to iphone6 

![qq 20170311171444](https://cloud.githubusercontent.com/assets/24618378/23822100/421a3216-0680-11e7-8d2e-c9df3c48d8e0.png)
![22](https://cloud.githubusercontent.com/assets/24618378/23822101/4366122a-0680-11e7-86c8-7552c651d246.png)

**Comment by Wlada** [comment]
I have iPhone6s and carousel works normally on mobile. What is problem exactly?

**Comment by crli** [comment]
hi hwyw it's me.   Directly through the Chrome browser debugging and Andrews system phone will appear the above bug, iPhone system phone is normal

**Comment by Wlada** [comment]
Hi

What is Andrews system ? 
I just tested on ios and android and can't reproduce problem.

The only thing is that on small screens if front/first slide is too big it will resize to screen width and it will look like slider.

**Comment by hwyw** [comment]
Andrews is  android 。。。I am not very good at English。。
I found that when the trigger resize event will be normal when the show may be some android mobile phone browser compatibility is not good，Maybe I did not handle some of the mobile browser compatibility，Thank you so
