### ISSUE TITLE
Is there any way to manually refresh

### ISSUE THREAD

**Issue by nini1294** [Wlada/vue-carousel-3d#14]
Hi,

I'm using the carousel to display a custom component that receives its data dynamically. When the parent component is loaded the data is empty, then it makes a request and uses the json response to populate the carousel slides. For me the carousel is empty until I resize the page, but then works correctly. Is there a way to manually refresh the carousel when my data is loaded?

A snippet of my code:

```
<carousel-3d v-bind:controlsVisible="true">
      <slide
        v-for="(item, ind) in data"
        v-bind:index="ind">
        <NewsItem v-bind:data="item"/>
      </slide>
</carousel-3d>
```

Thanks

**Comment by F-loat** [comment]
`this.$children[1]` is the `carousel-3d` component
``` javascript
this.$children[1].total = this.meals.length;
this.$children[1].goNext();
```
