### ISSUE TITLE
How can I pass values through javascript code instead of inline

### ISSUE THREAD

**Issue by elshahat** [Wlada/vue-carousel-3d#15]
I have an issue that I don't know how to add parameters through JS instead of inline like that:

```
    new Vue({
        el: '#slider3d',
        autoplay: true,
        loop: true,
        width: 600,
        height: 400,
        clickable: true,
        display: 5,
        data: {
            slides: 5
        },
        components: {
            'carousel-3d': Carousel3d.Carousel3d,
            'slide': Carousel3d.Slide
        }
    });
```
It's not working with me, is this code correct?

Also I need to know how can I use onSlideChange, onLastSlide etc..

There are many features found in this plugin but not clear on the documentation.

Thanks in advance.

**Comment by Wlada** [comment]
Hi,

Did you find a way how to implement component?
Take a look at jsfiddle examples on demos page.

**Comment by SVSagi** [comment]
Looking for the same. I could not find examples with values passed in javascript. 
Also, how do I choose different values in bootstrap media queries?

**Comment by Wlada** [comment]
Just added callback example on this examples page: https://wlada.github.io/vue-carousel-3d/examples/

**Comment by Wlada** [comment]
All good with this issue? Can this be closed?

**Comment by SVSagi** [comment]
I am looking initialise properties(Eg:- controlsVisible/width/space) like below, but doesn't seem to work

```
var vue1 = new Vue({
                          el: '#slider1',
                          props:
                          {
		    	      controlsVisible: true,
		  	      width: 400,
			      space: 500,
                              autoplay: false
	                  },
                          components: 
                          {
                                'carousel-3d': Carousel3d.Carousel3d,
                                'slide': Carousel3d.Slide
                          }
                  });
```
this doesn't seem to work either:
```
vue1.controlsVisible=true;
vue1.width=400;
vue1.space=500;
vue1.autoplay=true;
```

**Comment by Wlada** [comment]
Can you create jsfiddle example?
why you don't add html property to carousel?
`<carousel-3d :controls-visible="true" :clickable="false">`

**Comment by SVSagi** [comment]
I was using one of your examples and wanted to change some of the carousel properties dynamically at a later time.
I am OK to close this issue, if there no such option available at this time.

Thanks for the support :+1:

**Comment by Wlada** [comment]
Hi, 
Take a look this example
https://jsfiddle.net/Wlada/00pdp3tz/

It's possible to set some dynamic properties dynamic, but not all of them. 
For example, width and height can't because of some calculation in the background. This would be really good and probably right way to work, but at the moment is not possible. 
I will create a new task for this problem and see what can do in the future if it's even possible. 

Thanks

**Comment by Wlada** [comment]
#32

**Comment by Wlada** [comment]
Possibility to have dynamic properties #32  - Updated

Check my last comment on #32
