### ISSUE TITLE
3D-controls cover clickable area

### ISSUE THREAD

**Issue by tvld** [Wlada/vue-carousel-3d#17]
I like to be able to open an url by clicking on a div over the image. However, this will not work in combination with the 3D controls, as that div uses the whole width of the screen and not just the sides as seems logical. I added background to make it visible:

![screenshot from 2017-03-20 13-17-30](https://cloud.githubusercontent.com/assets/986182/24099458/accb2a5c-0d6f-11e7-9bcc-a6a507326a14.png)

I think we should not have *one* full width div there with the L/R buttons as children, but just the divs for the L/R buttons.
So not:
```scss
<div data-v-43e93932="" data-v-c06c963c="" class="carousel-3d-controls">
  <a data-v-43e93932="" href="#" class="prev"><span data-v-43e93932="">‹</span></a> 
  <a data-v-43e93932="" href="#" class="next"><span data-v-43e93932="">›</span></a>
</div>
```
but instead:
```scss
<a data-v-43e93932="" href="#" class="carousel-3d-controls prev"><span data-v-43e93932="">‹</span></a> 
<a data-v-43e93932="" href="#" class="carousel-3d-controls next"><span data-v-43e93932="">›</span></a>

```

**Comment by raphaelcunha** [comment]
temporarily change z-index: 9099 to z-index: -1 

 .carousel-3d-controls{
    z-index: -1 !important;
  }

**Comment by tvld** [comment]
You can do that, but then the controls can no longer be clicked ;) In that case you can disable them completely as well, I think...

**Comment by Wlada** [comment]
Problem fixed. I will deploy changes in next hour. 
Fix is easy, just put height to .carousel-3d-controls to 0.
