### ISSUE TITLE
Bug with dynamic data

### ISSUE THREAD

**Issue by kenyk7** [Wlada/vue-carousel-3d#18]
getSlideCount function: not updating when applying filter to data array vía computed property or getting vía ajax. 
Note: not update count slots or var total

**Comment by Wlada** [comment]
Can you create jsfiddle explanation ?

**Comment by kenyk7** [comment]
https://jsfiddle.net/hn9tjwob/

**Comment by kenyk7** [comment]
Check here:
https://codepen.io/kenyk7/full/RVrybb/

**Comment by kenyk7** [comment]
Please create branch dev for send pull request of here bug

**Comment by Wlada** [comment]
Created new develop branch, feel free to create new pull request. 
Thanks for contributing !
