### ISSUE TITLE
about width and height respensive

### ISSUE THREAD

**Issue by zhongziqi** [Wlada/vue-carousel-3d#20]
if this project responsive,cuz my project need to be responsive(means using in variety pc devices)

**Comment by Wlada** [comment]
it won't scale to fit 5 images, but instead it use overflow hidden. It will be fully functional.

**Comment by simondrabble** [comment]
What does this mean - fully functional? Or "overflow hidden"? Those features don't really answer the question.

Why can't we have responsive widths (e.g. width="80%") ?
