### ISSUE TITLE
Not working in Safari Browser

### ISSUE THREAD

**Issue by himanshutecstub** [Wlada/vue-carousel-3d#21]
I implement vue-carousel-3d in my website but it's not working in safari browser (I check in 5.34). check demo provide here which is not working in safari.

**Comment by Wlada** [comment]
I just checked and it works fine on my mac Safari version 10.1?
Also it works on my IPhone Safari ?

What operating system do you use ?

**Comment by himanshutecstub** [comment]
I am working on window 7 and website build in magento with bootstrap.
