### ISSUE TITLE
Documentation Update to fix `import Carousel3d from 'carousel-3d';`

### ISSUE THREAD

**Issue by mubaidr** [Wlada/vue-carousel-3d#27]
Documentation is required to be updated since the method to import the library is not valid mentioned inside global import headings. 

`import Carousel3d from 'carousel-3d';` should be `import Carousel3d from 'vue-carousel-3d';`

Otherwise import errors will occur stating that `carousel-3d` is not installed.

**Comment by Wlada** [comment]
Done

**Comment by mubaidr** [comment]
Please also update the same on the documentation website.

**Comment by Wlada** [comment]
Will do, Thanks!
