### ISSUE TITLE
Support for Internet Explorer ?

### ISSUE THREAD

**Issue by SVSagi** [Wlada/vue-carousel-3d#29]
Doesn't seems to work with Internet Explorer 11. Is it supported?
Works with Edge.

**Comment by Wlada** [comment]
Hi @SVSagi 
Thanks for reporting this. This is a bug, and it should work in IE11. 
Will see what I can do.

**Comment by Wlada** [comment]
The issue still present. There are some problems with setting slides/container height. 
vue-play doesn't work well with IE11 also and that complicates testing a bit more, but I will found some workaround for testing.

**Comment by Geminii** [comment]
Hi @Wlada,
First, a lot of thanks for your work. 
We will put our work in production and we have the same problem on IE. 
Hope you can fix this soon :)

**Comment by Wlada** [comment]
Just as a note, problem resolved. It will be pushed to master after complete testing is done.

**Comment by Wlada** [comment]
Now carousel supports IE11 and IE10

**Comment by Geminii** [comment]
Hi @Wlada 
Thanks a lot again for your work ;)
It works as well.
