### ISSUE TITLE
Enable controls without showing them?

### ISSUE THREAD

**Issue by tvld** [Wlada/vue-carousel-3d#3]
Really smooth! thank you ))

I like `:controlsEnabled="true"` but I dont want to see the two arrows... How can we do that?

**Comment by Wlada** [comment]
Hi @tvld ,
Thanks for comments!
Without controls is possible to control carousel by clicking on slide :clickable property needs to be true (it is by the default)

Also touch events will work if controls are disabled

As a feature maybe we can add a way to provide html code for arrows, but I will create separate issue for that.

Does this answers your question?

**Comment by tvld** [comment]
Thanks for quick reply. I had ` :controlsEnabled="false"` and the clicking did not work, but maybe I missed something. I suppose a simple `:showControls="false"` would be nice feature?

**Comment by tvld** [comment]
ok, the result is not so really great when I look at responsiveness :  https://www.lorinthe.com

```vue
<template>

  <carousel-3d class="slider"
    :display="3"
    :autoplay="false"
    :autoplayTimeout="3000"
    :autoplayHoverPause="true"
    :controlsEnabled="true">
    <slide v-for="(slide, index) in slides" :index="index">
      <img :src="assetDir + slide.img">
      <div class="caption">
        <span>{{ slide.caption }}</span>
      </div>
    </slide>
  </carousel-3d>

</template>

<script>

  import { Carousel3d, Slide } from 'vue-carousel-3d'

  export default {
    name: "slider",
    props: [
      'assetDir',
      'slides' // array with slide images stored in /static/img folder
    ],
    components: {
      Carousel3d,
      Slide
    }
  }
</script>

<style lang="scss">

$borderColor: #222;

.slider {
  height: 150px;
  .carousel-3d-slider {
    max-width: 90%;

  }
  .carousel-3d-slide {
    max-width: 100%;
    background: none;
    border: none;

  }
  img {
    max-width: 100%;
    border-left: 1px solid $borderColor;
    border-right: 1px solid $borderColor;
    border-top: 1px solid $borderColor;
    padding: 0;
    margin: 0;
  }
  .caption {
    background-color: $primaryDark;
    border-bottom: 1px solid #ccc;
    border-left: 1px solid $borderColor;
    border-right: 1px solid $borderColor;
    position: absolute;
    padding: 0;
    margin: 0;
    margin-top: -8px;
    font-size: $subscriptFontScale;
    width: 100%;
    color:$primaryWhite;
    span {
      text-shadow: 1px 1px #000;
      padding: 0 10px;
    }
  }
}


</style>

```

**Comment by Wlada** [comment]
Hi,

I will close this and create a new one. You are right, it's better to say controls-visible instead of controls-enabled

#4 Update controls-enabled to controls-visible
