### ISSUE TITLE
Possibility to have dynamic properties

### ISSUE THREAD

**Issue by Wlada** [Wlada/vue-carousel-3d#32]
More details on this example. 
https://jsfiddle.net/Wlada/00pdp3tz/

This is task for investigation and implementation

**Comment by Wlada** [comment]
Just as a note, problem resolved. It will be pushed to master after complete testing is done.

**Comment by mahrsbar** [comment]
Is this no longer possible? The jfiddle link is broken. I'm trying to implement dynamic properties.
