### ISSUE TITLE
Can I use it like this?

### ISSUE THREAD

**Issue by yk5tc** [Wlada/vue-carousel-3d#37]
"<script src="xxxxx"></script>"
no import and no npm install...

**Comment by Wlada** [comment]
You can reference file from "dist" folder

**Comment by yk5tc** [comment]
and then? how to use Carousel3d and Slide ？

**Comment by yk5tc** [comment]
i try to reference file directly，but it seems dosen‘t work

**Comment by Wlada** [comment]
You have to use ES import syntax

**Comment by mblackritter** [comment]
(In case someone else should still look this up)

@yk5tc, yes, you can:
```javascript
Vue.component('carousel-3d', Carousel3d.Carousel3d)
Vue.component('slide', Carousel3d.Slide)
```
