### ISSUE TITLE
Can't update full array

### ISSUE THREAD

**Issue by edDimensi** [Wlada/vue-carousel-3d#39]
Binding on index, not a good practice. Then i update full array, carousel not see it.
There are solutions? Thank you in advance

**Comment by Wlada** [comment]
Hi @edDimensi ,
I created js fiddle example, and it looks like it works fine
https://jsfiddle.net/pgrj35Ln/4/

**Comment by edDimensi** [comment]
Hm, i need some test. I can't understand, why my carousel not updated.

**Comment by Wlada** [comment]
Don't forget :count="length"
