### ISSUE TITLE
Events keep firing when not on component with carousel

### ISSUE THREAD

**Issue by sofanisba** [Wlada/vue-carousel-3d#40]
Just noticed that in the vue devtools, the event tab is showing that before-slide-change and after-slide-change are firing continuously even when I've navigated away from the component that has the carousel in it. Is there a navigation guard or some sort of lifecycle hook method you'd suggest to stop this behaviour/can I programatically stop/start the carousel?

This is what the carousel component looks like:
```
  <carousel-3d :controls-visible="true"
               :autoplay="true"
               :height="640"
               :display="3"
               :animationSpeed="1500">
    <slide v-for="(slide, i) in slides"
           :key="slide"
           :index="i"
           class="side-slide shadow-2dp">
      <img :src="slide"/>
    </slide>
  </carousel-3d>
```

**Comment by Wlada** [comment]
Zdravo Tamara,

Thanks for reporting this. I will create some test env on my local to reproduce this issue and will see what is best solution.

Feel free to create pull request if you resolve this first.

**Comment by sofanisba** [comment]
I'll take a look over the weekend.

Another note: in my case it's a local usage rather than global import. Don't know if that changes anything.

**Comment by Wlada** [comment]
This is done. Deployed to master. Version 0.1.16
https://github.com/Wlada/vue-carousel-3d/commit/82f0ab961b5205fc5c380679f9c91193b23b7498

**Comment by sofanisba** [comment]
Hvala!
