### ISSUE TITLE
SSR, Nuxt bug: first slide doesn't show up

### ISSUE THREAD

**Issue by vadimsg** [Wlada/vue-carousel-3d#48]
I'm using Nuxtjs and currently I can get it to work in dev mode but when I make a production build it doesn't show the first (index 0) slide. Slider works fine and other slides are showing but not the first one.
Maybe some one has idea how to fix it or had something similar? Great slider but it definitely needs full SSR support.

**Comment by vadimsg** [comment]
Fixed it by delaying carousel initialization till mounted is triggered. Interesting.

**Comment by neeraj022** [comment]
how do I make the carousel initialisation ? 

Carousel 3d doesn't work if I import it directly in the page, it only works by making it a plugin with ssr disabled.

**Comment by dr1ss** [comment]
Anyone succeeded on using vue-carousel-3d with nuxt ? 
If so, a guide would be great

**Comment by jonzee** [comment]
to use `vue-carousel-3d` with nuxt:
* add file `plugins/index.js` with code
```javascript
import Vue from 'vue'
import VueCarousel3d from 'vue-carousel-3d'
Vue.use(VueCarousel3d)
```
* add in `nuxt.config.js`:
```javascript
module.exports = {
   ...
   plugins: [{
      src: '~/plugins',
      ssr: false,
   }],
   ...
}
```
* in your component wrap `vue-carousel-3d` with `<no-ssr></no-ssr>`
```javascript
<no-ssr placeholder="Loading...">
   <carousel-3d>
      <slide v-for="(slide, i) in slides" :index="i" :key="i" />
   </carousel-3d>
</no-ssr>
```
Btw. this is temporary solution, `vue-carousel-3d` should work with `nuxt` & `ssr` (this is bug!)

**Comment by icarito** [comment]
@vadimsg I wonder how you "delaying carousel initialization till mounted is triggered".

BTW agreed this is some kind of bug / server side rendering issue and this bug should be reopened.
I have been able to "reproduce" by using the Playground and removing all slides and then adding many slides **very quickly**. You will then see the middle slide remain with `visibility: hidden` and `opacity: 0`. Will open a new bug as it's not necessarily related.

**Comment by icarito** [comment]
My bad, there's no need to do "very quickly". Just start from zero. With zero slides, there won't be a slide selected once you start adding slides. Documented finding in #73

**Comment by icarito** [comment]
Maybe it's a hack but I was able to show the first slide in Nuxt by using this:

```html
<carousel-3d ref="treeExplorer">...
```
```javascript
export default {
...
  updated: function () {
    this.$refs.treeExplorer.goSlide(this.$refs.treeExplorer.currentIndex
  }
...
}
```

**Comment by fergardi** [comment]
Thank you @icarito, this hack worked for me as well.

**Comment by Wlada** [comment]
How we can include this fix in develop branch? Can someone create pull request?

**Comment by ScreamZ** [comment]
I'm facing a similar issue when sometimes the carousel doesn't show any slide (or only the first one) and is not playing. Looks like the slider are stacked below first one) if i change window size, it start again

**Comment by baharnadimi** [comment]
> Maybe it's a hack but I was able to show the first slide in Nuxt by using this:
> 
> ```
> <carousel-3d ref="treeExplorer">...
> ```
> 
> ```js
> export default {
> ...
>   updated: function () {
>     this.$refs.treeExplorer.goSlide(this.$refs.treeExplorer.currentIndex)
>   }
> ...
> }
> ```

thanks so much

**Comment by ahadihadi** [comment]
can fix simply by initializing an array with enough count of empty objects. instead of:
```
  data: {
    events: [],
  },

```
```
usaer:
  data: {
    events: [{}, {}, {}, {}, {}],
  },
```
