### ISSUE TITLE
Allow users to define left/right arrow controls with property 

### ISSUE THREAD

**Issue by Wlada** [Wlada/vue-carousel-3d#5]

**Comment by leninisabel** [comment]
Hi, just wanted to see if there was any progress on this

**Comment by Wlada** [comment]
Hi @leninisabel ,

Sorry to say but at the moment I'm overloaded with work and private stuff. Will try to resolve this ASAP.

**Comment by leninisabel** [comment]
No problem, just checking up that’s all. I know the file that needs to be updated but Im not that good at JS yet, I wouldn’t know how to update the .vue file and test it

[ConnectWise]<https://www.connectwise.com>

Lenin Isabel

Web Designer

Email: LIsabel@ConnectWise.com<mailto:LIsabel@ConnectWise.com>

Office: (813) 739-8580



[http://img03.en25.com/EloquaImages/clients/ConnectwiseInc/%7B69be81d9-8a92-493a-afad-aa46bcf98514%7D_cw-masterbrand2.png]<https://www.connectwise.com/solutions/connectwise-business-suite>

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by Wlada** [comment]
I'll do my best to finish that this week. Probably will get some time during the weekend.

**Comment by Wlada** [comment]
This one is done

Check "Custom Controls" example:
https://jsfiddle.net/Wlada/r6auc7bh/  
or on examples page
https://wlada.github.io/vue-carousel-3d/examples/
API page:
https://wlada.github.io/vue-carousel-3d/guide/

**Comment by leninisabel** [comment]
Thank you!

[ConnectWise]<https://www.connectwise.com>

Lenin Isabel

Web Designer

Email: LIsabel@ConnectWise.com<mailto:LIsabel@ConnectWise.com>

Office: (813) 739-8580



[http://img03.en25.com/EloquaImages/clients/ConnectwiseInc/%7B69be81d9-8a92-493a-afad-aa46bcf98514%7D_cw-masterbrand2.png]<https://www.connectwise.com/solutions/connectwise-business-suite>

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by ziat1988** [comment]
Hello, 
Can we have control on the aria-label of the left/right arrow? 
For now they are "Next slide" / "Previous slide" , so is it possible to change that label text?
Thanks
