### ISSUE TITLE
how to change the height?

### ISSUE THREAD

**Issue by Anne327** [Wlada/vue-carousel-3d#51]

**Comment by inzaghihao** [comment]
<carousel-3d :width="460" :height="340" :space="250" :display="3" >

**Comment by inzaghihao** [comment]
<carousel-3d :perspective="0" :width="460" :height="340" :space="250" :display="3" class="carousel-3d">

**Comment by opax556783** [comment]
<div id="example">
  <carousel-3d :width="200" :height="400">
    <slide v-for="(slide, i) in slides" :index="i">
      <span class="title">You know</span>
      <p>You know, being a test pilot isn't always the healthiest business in the world.</p>
    </slide>
  </carousel-3d>
</div>
