### ISSUE TITLE
How can i Jump to the specified slide?

### ISSUE THREAD

**Issue by inzaghihao** [Wlada/vue-carousel-3d#52]
i want pagination ,click index jump to slide, thank you

**Comment by yjw0628** [comment]
html: 
`<carousel-3d ref="mycarousel">
  <slide :index="0">Slide 1 Content</slide>
  <slide :index="1">Slide 2 Content</slide>
</carousel-3d>`


javascript: 
`
this.$refs.mycarousel.goSlide(num)
`
