### ISSUE TITLE
android 4.4 below does not have animation effect

### ISSUE THREAD

**Issue by MarvinXu** [Wlada/vue-carousel-3d#53]
should add prefixes for css3 properties

**Comment by Wlada** [comment]
Hi @MarvinXu 
I did not test android 4.4 devices. Can you contribute?
At the moment I'm tied up in some work, and can't spend some time on vue-carouse-3d

Thanks

**Comment by MarvinXu** [comment]
ok. I will give it a shot.

**Comment by Wlada** [comment]
not supporting android 4
