### ISSUE TITLE
Interface to return data problems（接口返回数据问题）

### ISSUE THREAD

**Issue by Aliceco** [Wlada/vue-carousel-3d#58]
使用 $http 访问接口得到的数据 使用v-for 循环出来 的数据 不能马上得到，需要等待2秒才出现，而且只能出现一张，而且刷新也是这样，需要你去谷歌浏览器切换 浏览模式（如果 PC模式，手机模式才显示出来），我测试发现 transition、transform样式不见了

Use $HTTP access interfaces to get data using v - data not immediately get the for loop, needs to wait for 2 seconds to appear, and can only appear a piece, and refresh, too, need you to go to Google browser browse mode switch (if PC mode, mobile phone mode is displayed), I found the transition test, the transform style is missing

**Comment by Aliceco** [comment]
我看了一下源码：可能是这个造成的
Slide.vue里面的 
isCurrent () {
                return this.index === this.parent.currentIndex
},

**Comment by Aliceco** [comment]
解决了   官方说了最好提前把所有属性声明好。不管有没有数据也给他一个null  比如 你在data 定义了一个变量来循环 slides = []   然后接口那边 赋值给它 ，  你data 应该写成 slides = [null]

**Comment by Wlada** [comment]
Can you add some code? Js fiddle would be great. Thanks
