### ISSUE TITLE
Support for even number of slides

### ISSUE THREAD

**Issue by ryno1234** [Wlada/vue-carousel-3d#59]
It appears that any even number of slides (above 2) is not supported.

Example: If I have 4 slides, only 3 are shown and the 4th is "hidden" until I shift the current slide by one position either way, at which point one of the other slides is now hidden.

Interestingly, support for 2 slides **does** exist and will show a center slide as well as one singular slide off to the side of the center slide.

Is there support for an even number of slides that I just haven't found yet? If not, we will either have to use another tool to accomplish what we're trying to accomplish unfortunately or make the change our self and send a pull request.

If an even number of slides is not supported, do you have a sense of the effort that would be required to implement this? I would like to investigate the feasibility of making the change myself but would like to get a better grip on what all that might entail.

Thank you.

**Comment by Wlada** [comment]
@ryno1234 I believe that this is done now in version 0.1.19. You created a pull request. 
Code merged and version updated. Also, I added "bias" property to documentation.

Thanks again

**Comment by ryno1234** [comment]
Thank you!
