### ISSUE TITLE
startIndex

### ISSUE THREAD

**Issue by sh4n3** [Wlada/vue-carousel-3d#61]
I have set :startIndex="2" on the <carousel-3d> tag, however the slide assigned index of 0 is still showing first, and in the vue console the startIndex in the props column is still showing as 0.

https://wlada.github.io/vue-carousel-3d/api/#startIndex

Anyone else run into this issue?

**Comment by Wlada** [comment]
Hi @sh4n3 

Define like this:
`  <carousel-3d :count="slides.length" :start-index="2">
    <slide v-for="(slide, i) in slides" :index="i">
      <h1>{{slide.name}}</h1>
    </slide>
  </carousel-3d>
`

html attributes are now case sensitive and that is why is not working.

**Comment by shernaz** [comment]
Is there a way to set currentSlide, on some events ?
