### ISSUE TITLE
goSlide not working

### ISSUE THREAD

**Issue by JKHeadley** [Wlada/vue-carousel-3d#66]
Hello, first of all great project!  I'm trying to programatically jump to a slide using the goSlide function.  The carousel seems to jump to the correct index, however the slide disappears.  Do you know what could cause this?  See below for an example image:

![screen shot 2017-12-25 at 11 00 35 pm](https://user-images.githubusercontent.com/12631935/34349688-7a0db5a0-e9c7-11e7-9555-97cc75a7b6d0.png)

**Comment by Wlada** [comment]
Hi @JKHeadley 

It's really hard to help without code. Can you create jsfiddle with bug example?
