### ISSUE TITLE
Plugin doesn't work after page resize

### ISSUE THREAD

**Issue by TheDeveloperTom** [Wlada/vue-carousel-3d#69]
1. open a page with vue-carousel-3d slider.
2. resize the page, and plugin stop working. (see attached images)

**1. before resize**
![image](https://user-images.githubusercontent.com/25426552/34928343-8bf18c70-f9c5-11e7-9c22-9dd3a0c2ac2a.png)

**2. after resize**
![image](https://user-images.githubusercontent.com/25426552/34928365-b78d4428-f9c5-11e7-9a22-ce6f510e41cd.png)

**Comment by Wlada** [comment]
Can you create an example on jsFiddle ? 

Everything works fine for me. Also check examples on https://wlada.github.io/vue-carousel-3d/examples/
