### ISSUE TITLE
When adding a new slide - is it possible to jump to it.

### ISSUE THREAD

**Issue by etabrizi** [Wlada/vue-carousel-3d#74]
Just been working with this feature which is great. Just wondering, when you add a new slide to an array, which is used as a loop for the carousel. Is it possible to jump to the new added item? 

Some way of using a method to detect a new item added and cycling to that particular slide? That would be great.

**Comment by MichaelT372** [comment]
#92 would solve this by having a `showIndex` prop that you could bind to `mySlideArray.length-1`

Bandaid for now is to add a `ref` to the carousel and use that to call the `goSlide` method for example after your new slide is added to the array do `this.$refs.myCarousel.goSlide(mySlidesArray.length-1);`

**Comment by Wlada** [comment]
Updated documentation/exapmles with how to use goToSlide function. 
Check : https://wlada.github.io/vue-carousel-3d/examples/
