### ISSUE TITLE
Use in SSR

### ISSUE THREAD

**Issue by ScreamZ** [Wlada/vue-carousel-3d#77]
Hi, really like the component but I would like to know if there is a way to use it while using SSR.

Currently I'm getting an error specifying that document is not defined, which is normal because it is not...

Are you planning to do something about that ? Or should I render a simplified version without slider in SSR and let the normal mode take the hand after that ?

Regards

**Comment by Wlada** [comment]
SSR?

**Comment by ScreamZ** [comment]
Server Side Rendering.

Atm I patched with a non-carrousel on server side, which load the library on the client side.

**Comment by ZaidRehman** [comment]
The problem is not solved its just patched. Can we use this library with full SSR support?
