### ISSUE TITLE
difference in clicking (next and prev) and swipe

### ISSUE THREAD

**Issue by michapixel** [Wlada/vue-carousel-3d#81]
https://jsfiddle.net/michapixel/y6b8gns4/5/

see, when you swipe the images left and right from the center are pre-rendered when dragged to the center. if i click left or right trigger, the placeholder for the next is empty and pops in.

**Comment by michapixel** [comment]
plus: animationSpeed does nothing in my example

**Comment by michapixel** [comment]
Well 
```
.carousel-3d-slide {
                    visibility: visible !important;
}
```
fixes this temporarely, at least for me.

**Comment by ee07b577** [comment]
same issue for me
