### ISSUE TITLE
[Feature request] carousel indicators for easy navigation 

### ISSUE THREAD

**Issue by Nethravathi-K** [Wlada/vue-carousel-3d#88]
Hi,

I'm a newbie to coding, I found this as a great plugin, I went through the document , unfortunately I couldn't find an option for activating the indicators , it will be a great plugin if the indicators for the same is added. 

Thanks,
Nethra

**Comment by martijndewit** [comment]
https://github.com/Wlada/vue-carousel-3d/issues/43
