### ISSUE TITLE
Change the slide programmatically

### ISSUE THREAD

**Issue by saazrai** [Wlada/vue-carousel-3d#9]
Is it possible to change the slide programmatically?

I want to be able to change the slide upon certain event by assigning the current slide index.

**Comment by Wlada** [comment]
Hi Saazrai,

Yes, it's possible.  Here is the jsfiddle link
https://jsfiddle.net/Wlada/sLmw67t8/

I will add this documentation in next version.

**Comment by saazrai** [comment]
Awesome! What I needed was goSlide() which was in your source code.

Documentation will help. Thanks

**Comment by Wlada** [comment]
Yes, you can use goSlide(index) and pass index of slide where you wan't to go. 
I will close this issue once documentation is updated

**Comment by Wlada** [comment]
Example added

**Comment by MrWangwj** [comment]
How do you use goSlide(index)

**Comment by Zip753** [comment]
@Wlada Where can we find the added example? I can't see it anywhere and it's a pretty important chunk of documentation IMO, the similar question was asked in #52 most probably because of the missing example, and I myself only found the answer through this GH issue. Thanks!

**Comment by tsauvajon** [comment]
I can't find the example either...
